import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";


const inter = Inter({subsets: ["latin"]});

export const metadata = {
  title: "Droogger",
  description: "Generated by GBP",
};

export default function RootLayout({ children }) {

  // let header = (
  //  <header className="site-header">
  //   <Link href="/">
  //     <h1 className="site-title">Droogger</h1>
  //   </Link>
  //  </header>
  // )
  // let footer = (
  //  <footer className="site-footer">
  //     <p className="disclaimer">
  //       Disclaimer: This site provides general information and does not endorse or promote the theories it covers.
  //     </p>
  //     <p className="credit">Made by GBP</p>
  //  </footer>
  // ) 
    let header = (
    <header className="site-header">
      <Link href="/" className="site-title">
        Droogger
      </Link>
      <nav className="site-nav">
        <Link href="/about">About</Link>
      </nav>
    </header>
  );

  let footer = (
    <footer className="site-footer">
      <p className="disclaimer">
        Disclaimer: This site provides general information and does not endorse or promote the theories it covers.
      </p>
      <p className="credit">Made by GBP</p>
    </footer>
  );
  return (
    <html lang="en">
      <body className={inter.className}>
        {header}
        {children}
        {footer}
      </body>
    </html>
  );
}
